name: project deployment
on:
  push:
    branches: [master]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: run ssh
        uses: appleboy/ssh-action@v1
        with:
          host: 183.101.189.204
          username: test
          password: qwer1234
          port: 103
          script: |
            rm -rf ./ciCdProject
            git clone https://github.com/why48382/ciCdProject
            cd /home/test/ciCdProject/
            ./gradlew bootJar
            docker rm -f gitback
            docker image prune -f
            docker image build -t gitback:latest .
            docker run -d --name gitback -p 8080:8080 gitback:latest
